descs = {
    'Batootha': 'Boosts both Atk & Def by 30%, and damaged dealt by Spark by 50%',
    'Red Pelt': 'A rare, red beast pelt with both high hardness and flexibility.',
    'Blaze Fang': 'A fang from a fire eating dragon used to chew flames.',
    'Malice Jewel': 'Boosts Atk, Def, Rec & max HP by 30%',
    'Divine Crown': 'Adds Chance of BB Gauge Greatly Filling when Attacked',
    'Soul Spear': 'Adds Chance of Absorbing HP when Attacking',
    'Drevas': 'Boosts Def and max HP by 30% and negates all status ailments',
    'Phoenix Eye': 'HP increases after every turn',
    'Shiny Jewel': 'A bright jewel that exists within the body of Laguna Rex.',
    'Alzeon Pearl': 'BB gauge fills much faster when obtaining BC',
    'Demon Crown': 'Boosts BB gauge every turn & adds chance of BB gauge boost when damaged',
    'Soul Gun': 'Adds slight chance of Weak, Injury & Paralysis when attacking',
    'Demon Eye': 'A crystal with a silvery shine that holds immense magic.',
    'Royal Shield': 'Boosts Def by 50% for First 3 Turns',
    'Phoenix Eye': 'HP recovers greatly after every turn',
    'Fiend Fang': 'Adds Possible Injury Effect and a Chance to Absorb HP from normal attacks',
    'Cure Bracer': 'Boosts Drop Rate of HC when Attacking',
    'Elder Hat': 'Small reduction in BB gauge required for BB',
    'Divine Blade': 'Boosts Atk & Def by 100% for first 2 turns',
    'Magic Ore': 'BB gauge fills greatly after every turn',
    'Crown Light': 'Increases resistance to Poison, Sick, and Curse',
    'Refined Gem': 'Invalidates All Status Ailments',
    'Sky Fang': 'The fang of an ancient beast, rumored to have fallen from the sky.',
    'Solar Helm': 'Adds Chance of 30% of Damage Taken Being Recovered',
    'Royal Bud': 'Increases damage dealt during Spark by 25%',
    'Undying Flame': 'An undying flame that doesn\'t burn nor scotch',
    'Zeus\'s Robe': 'Greatly Recovers HP when an Enemy is Defeated',
    'Alter Blade': 'Boosts all abilities when HP is full',
    'Guardian Cloak': 'Boosts DEF by 360% when unit HP drops below 35%. Slight increase of BC drop when attacking.',
    'Demon Bow': 'Adds chance of inflicting a random status ailment when attacking',
    'Divine Spear': 'Adds Chance of Ignoring Enemy\'s Defense when Attacking',
    'Seph Feather': 'A feather dropped from an auspicious bird in the Agni region.',
    'Zelnite Ring': 'Boosts Drop Rate of Zel when Attacking',
    'Fairy Choker': 'Substantially Increases Drop Rate of BC and HC when Near Death',
    'Suzu Nut': 'A ancient nut cherished by many, said to have tranquilizing powers.',
    'Giant Stone': 'Boosts All Abilities when BB Gauge is Below Half',
    'Spirit Eye': 'Eyes on the back of Marian that hide strong magical powers.',
    'Blue Bone': 'A blue bone from a giant beast.',
    'Dandelga': 'Boosts Atk and max HP by 30% and increases BB gauge after every turn',
    'Red Bone': 'A red bone from a mysterious beast.',
    'Demon Rifle': 'Adds Possible Weak Effect to Normal Attack',
    'Famous Blade': 'Boosts Atk by 5%',
    'Ruin Tear': 'A mysterious liquid that leaked out from the head of Van Lucy.',
    'Shiny Armor': 'Boosts Max HP by 20%',
    'Gilded Pearl': 'Boosts Def and Rec when HP is Below Half',
    'Smooth Stone': 'A mineral required for the refining of essential components in certain materials.',
    'Summoner Hat': 'Slightly reduces the amount of BB gauge needed for its use',
    'Electric Shield': 'Decreases Thunder Damage by 15%',
    'Earth Eye': 'A crystal that holds the power of earth.',
    'Lightning Shield': 'Decreases Thunder Damage by 30%',
    'Frozen Pelt': 'An elastic pelt from an ice beast that is also very durable.',
    'Force Amulet': 'Boosts Atk by 5%, Def by 10% and Rec by 15%',
    'Sand Bone': 'The bone of a strange dotted animal from the Mirvana region.',
    'Blue Grass': 'An important medicinal plant that\'s highly effective for recovery.',
    'Holy Crown': 'Adds Chance of BB Gauge Slightly Filling when Attacked',
    'Green Bone': 'A giant green beast bone.',
    'Fairy Fruit': 'A fruit from Meru-Meru that takes countless years to grow.',
    'Hoku Nut': 'The nut of an annual plant that hightens the self-defense instinct.',
    'Evil Halberd': 'Adds slight chance of inflicting a random status ailment when attacking',
    'Godly Statue': 'Slightly reduces the consumption of BB gauge',
    'Don Nut': 'An anti-poison nut native to much of Elgaia and Grand Gaia.',
    'Death Cannon': 'Adds possible Weak effect to normal attack',
    'King\'s Crown': 'Adds chance of BB substantially filling when attacked',
    'Old Dagger': 'Adds slight chance of Poison, Sick & Curse when attacking',
    'Dragon Stud': 'Add chance of BB gauge greatly filling when attacking',
    'Drain Spear': 'Adds chance of absorbing HP when attacking',
    'Red Bug': 'A small red ladybug.',
    'Flesh Armor': 'Boosts Def and Max HP by 10%',
    'Cursed Sword': 'Adds possible Curse effect to normal attack',
    'Gold Drop': 'A drop of water from Craster\'s Ravine, west of Elgaia.',
    'Ogre Lance': 'Adds possible Injury effect to normal attack',
    'Spring Stone': 'A transparent stone found in a particularly clear spring. ',
    'Flame Jewel': 'A red hot jewel that was once the heart of Claudalus.',
    'Thief Bracer': 'Boosts Drop Rate of Items when Attacking',
    'Aegis Cloak': 'Boosts DEF by 330% for the first 2 turns. BB guage fills faster when obtaining BC.',
    'Guardian Eye': 'A mysterious golden crystal that has unknown effects and uses.',
    'Cobalt Pelt': 'A hard blue shell that covered Medronomus.',
    'Dragon Ring': 'Adds chance of BB gauge filling when attacking',
    'Monster Robe': 'Adds Chance of Damage Taken being Decreased by 20%',
    'Golden Bug': 'A beetle that eats gold dust and stores it as gold in its body.',
    'Wicked Stone': 'An evil stone often used as a decoration by nobles.',
    'Growth Light': 'Increases Resistance to Sick',
    'Electric Blade': 'Boosts Max HP, Def by 5% and Increase Thunder Atk for Thunder Type Unit by 20%',
    'Sol Creator': 'Greatly boosts drop rate of BC when attacking',
    'Havoc Axe': 'Massively boosts critical hit rate',
    'Gold Bangle': 'Greatly boosts effectiveness of HC',
    'Luna Creator': 'Greatly boosts drop rate of HC when attacking',
    'Acute Eye': 'Smoky-looking drops that release a putrid gas, found among clusters of special fungi.',
    'Divine Gem': 'Boosts Atk when BB gauge is full',
    'Holy Cane': 'Boosts Rec by 15%',
    'Song Jewel': 'Boosts Atk by 10%, Def by 20% and Rec by 30%',
    'Dark Pelt': 'A flawless black wing from Reduhark.',
    'Terra Shield': 'Decreases Earth Damage by 30%',
    'Dark Claw': 'A claw dyed with the blood of Reduhark.',
    'Giant Pelt': 'The pelt from a massive and immensely powerful beast.',
    'Limbo Stone': 'Increases Def, Rec, and max HP by 10%',
    'Ominous Eye': 'An evil eye that floats around Nalda Delia.',
    'Hard Bone': 'A very hard material said to be the fossil of an ancient demon.',
    'Phantom Eye': 'An eye from one of the many speckles on Mistzug\'s body.',
    'Green Bug': 'A small green ladybug.',
    'World Lance': 'Adds chance of Poison, Sick & Curse when attacking',
    'Wicked Hand': 'A black iron arm from Van Nader infused with magic.',
    'Demon Lance': 'Adds slight chance of ignoring enemy\'s Def when attacking',
    'Fate Stone': 'A stone that has special elemental attack powers.',
    'Lightning Blade': 'Boosts Max HP, Def by 10% and Increase Thunder Atk for Thunder Type Unit by 35%',
    'Chosen Blade': 'Boosts Atk by 35%',
    'Gold Coin': 'Coin that could fetch a decent amount of Zel',
    'Cursed Robe': 'Recovers Some HP when an Enemy is Defeated',
    'Dark Jewel': 'A jewel Reduhark created from condensed darkness.',
    'Mystic Lantern': 'Boost ATK, DEF, REC, HP by 15%. Slight CRIT rate up.',
    'Divine Crest': 'Recovers Some HP when a Battle is Won',
    'Honor Pelt': 'Unique pelts distributed by the Summoners\' Council.',
    'Stealth Robe': 'Removes Chance of Being Targeted when HP is Below Half',
    'Poison Shiv': 'Adds Possible Poison Effect to Normal Attack',
    'Vampire Spear': 'Adds chance of absorbing some HP when attacking',
    'Thunder Eye': 'A crystal that holds the power of thunder.',
    'Blaze Pelt': 'A scorching, uncooled scale from Claudalus.',
    'Forever Bone': 'A beautiful bone that has an eternal shine like silver.',
    'Burst King': 'Boosts critical hit rate when HP is full',
    'Brute Pelt': 'The pelt of an extremely ferocious beast that resides in the lands of Agni.',
    'Queen Jewel': 'The jewel rumored to be the origin of Marian\'s power.',
    'Ember Armor': 'Boosts Max HP by 30%',
    'Challenger': 'Boosts all abilities when BB gauge is above half',
    'Brown Grass': 'Meant to grow into a tree, but turned into bark-colored grass.',
    'Blue Dragon': 'Boosts max HP & Atk by 20%',
    'Green Drop': 'Drops of water that gush forth all over Elgaia and Grand Gaia.',
    'Fallen Eye': 'A crystal from Van Lucy in the shape of an eyeball.',
    'Inferno Shield': 'Decreases Fire Damage by 30%',
    'Faint Light': 'Increases Resistance to Weak',
    'Multi Slayer': 'Recovers HP when an enemy is defeated',
    'Beast Blade': 'Boosts Atk by 15%',
    'Light Helm': 'Adds Chance of 10% of Damage Taken Being Recovered',
    'Weak Shard': 'Negates Weak',
    'Yellow Bone': 'The bone of a beast fossilized after sitting for countless years.',
    'Inferno Blade': 'Boosts Max HP, Def by 10% and Increase Fire Atk for Fire Type Unit by 35%',
    'Phantom Pike': 'Adds possible Sick effect to normal attack',
    'Bright Shard': 'Negates Poison, Sick, and Curse',
    'Disaster Eye': 'A disastrous eye that floats around Nalda Delia.',
    'Luna Laguliz': 'Boosts HP, Atk, Def, Rec, and Critical Rate by 25%',
    'Jade Stone': 'A stone that flickers in a beautiful, faint green color.',
    'Daze Claw': 'A jet-black claw from one of the many arms of Mistzug.',
    'Rhoa Feather': 'A feather from the Rhoa, often called the bird of good fortune.',
    'Godly Staff': 'Boosts Rec by 25%',
    'King Shield': 'Boosts Def by 25%',
    'Skill Bracer': 'Boosts Drop Rate of BC when Attacking',
    'Verdant Pelt': 'A hard green shell that covered Granomus.',
    'Hero Stone': 'Boosts All Abilities when BB Gauge is Above Half',
    'Cursed Sabre': 'Adds Possible Curse Effect to Normal Attack',
    'Dark Helm': 'Adds Chance of Returning 50% of Damage Taken to Enemy when Attacked',
    'Thief Cloak': 'Greatly boosts BC, HC, Zel, Karma, and Item drop rate',
    'Over Killer': 'Adds chance of BB gauge slightly filling when attacked',
    'Water Shield': 'Decrease Water Damage by 15%',
    'Solid Pelt': 'A scale from a fire eating dragon that can never burn.',
    'God Stone': 'A magical stone that radiates god-like energy.',
    'Honor Drop': 'Unique drops distributed by the Summoners\' Council.',
    'Green Pelt': 'The light-green pelt of a common beast.',
    'Royal Shard': 'Negates Weak, Injury, and Paralysis',
    'Evil Shard': 'BB gauge increases after every turn',
    'Beast Bracer': 'Increases drop rate of Karma when attacking',
    'Dark Lance': 'Adds chance of Weak, Injury & Paralysis when attacking',
    'Demon Dress': 'Adds very slight chance of decreasing damage received to 1point',
    'Life Shield': 'Boosts Def & Rec by 20%',
    'Grand Shield': 'Boosts Def by 35%',
    'Forge Stone': 'A stone containing the flames of hell itself.',
    'Weary Shard': 'Negates Injury',
    'Dragon Seal': 'Boosts Def by 10%',
    'Green Claw': 'The green fossil of a great beast\'s claw obtainable anywhere.',
    'Sacred Gem': 'Greatly boosts all abilities when BB gauge is full',
    'Hope Stone': 'Greatly Increases Def and Rec when Near Death',
    'Angel Tear': 'Miraculous drops said to have fallen from the eyes of a goddess.',
    'Green Fang': 'The easily obtainable green fossil of a great beast\'s fang.',
    'Brave Emblem': 'Boosts Atk and Rec by 20%, HP and DEF by 10%, and increases resistance to status ailments',
    'Angelic Foil': 'Boosts Atk by 75% for first 2 turns',
    'Ghost Jewel': 'A jewel rumored to give Mistzug his power.',
    'Bara Nut': 'A supremely pungent nut from the Bara tree that can heal paralysis.',
    'Demon Robe': 'Recovers HP when an Enemy is Defeated',
    'Comet Bug': 'A bug found in the mineral mountains. It makes its nest with silver.',
    'Beast Armor': 'Boosts Max HP by 10%',
    'Stupor Shard': 'Negates Paralysis',
    'Wise Mask': 'Increases Chance of Being Targeted',
    'Cursed Light': 'Increases Resistance to Curse',
    'Hades Claw': 'The claw of a beast said to have come from the underworld.',
    'Karma Stone': 'Magical hardened lava from a volcano many threw themselves into.',
    'Royal Aegis': 'Boosts Atk and Def by 20%, and Absorbs HP from normal attacks.',
    'Red Stone': 'A stone said to increase vitality that emits a crimson glow.',
    'Magical Axe': 'Greatly Boosts Critical Hit Rate',
    'Ill Shard': 'Negates Sick',
    'Worn Fang': 'The fossil of a large fang from a legendary beast.',
    'Purple Drop': 'Very valuable drops that are said to have fallen from the heavens.',
    'Timber Nut': 'A nut that grows on the back of Laguna Rex.',
    'Demon Claw': 'A claw from a fanged demon with two massive horns.',
    'Phoenix Wing': 'Restores HP every turn & adds chance of slight HP recovery when damaged',
    'Koka Nut': 'The nut of a perennial plant that increases aggression when eaten.',
    'Giant Claw': 'A monster claw so large it can’t be removed by any but the strongest of individuals.',
    'Beast Spear': 'Adds Possible Injury Effect to Normal Attack',
    'Fire Shield': 'Decreases Fire Damage by 15%',
    'Brute Claw': 'The rigid claw of an extremely ferocious beast that resides in the lands of Agni.',
    'Lizeria Gem': 'Boosts Atk and Def by 15%',
    'Crypt Fang': 'A fang from a demon locked away in a prison in the abyss.',
    'Blue Claw': 'The blue fossil of a great beast\'s claw found in the Morgan region.',
    'Holy Blade': 'Boosts Atk by 10%',
    'Glass Crown': 'Adds Chance of Returning 20% of Damage Taken to Enemy when Attacked',
    'Broken Light': 'Increases Resistance to Injury',
    'Sentry Cane': 'Boosts Rec by 10%',
    'Red Grass': 'An important medicinal plant that\'s highly effective in fortification.',
    'Legwand Gem': 'Boosts Atk, Def, Rec, and HP by 25%',
    'Zel Ring': 'Boosts drop rate of Zel when attacking',
    'Zombie Jabot': 'Substantially Increases Drop Rate of BC and HC when HP is Below Half',
    'Purple Fang': 'A seed as sharp as a fang from the Purple Emperor flower.',
    'Honor Claw': 'Unique claws distributed by the Summoners\' Council.',
    'Blessed Robe': 'Adds chance of damage taken being decreased by 30%',
    'Holy Emblem': 'Greatly Recovers HP when a Battle is Won',
    'God Sword': 'Boosts Atk by 30%',
    'Star Shield': 'Boosts Def by 20%',
    'Frozen Claw': 'A hard claw from an ice beast that can be used to climb glaciers.',
    'Vine Lance': 'Adds Possible Sick Effect to Normal Attack',
    'Cordelicite': 'Increases Atk and Def by 10%',
    'Silver Aegis': 'Boosts Atk and Def by 15%, and Absorbs HP from normal attacks.',
    'White Cane': 'Boosts Rec by 5%',
    'Divine Stone': 'Boosts All Abilities when BB Gauge is Full',
    'Flag Flower': 'Greatly increases damage dealt during Spark, and drop rate of BC & HC',
    'Cosmic Dust': 'Negates all status ailments and increases HP by 20%',
    'Thief Guards': 'Increases drop rate of Zel and Karma when attacking',
    'Gold Ingot': 'A valuable piece of gold',
    'Dark Armor': 'Boosts Max HP by 35%',
    'Blue Stone': 'A precious stone that has a powerful spiritual magic.',
    'Yomi Feather': 'The molted feathers of the magical Yomi bird that hold a hidden power.',
    'Exyl Shield': 'Boosts Def by 75% for first 3 turns',
    'Fallen Hand': 'A white copper arm from Van Lucy infused with magic.',
    'Red Fang': 'The red fossil of a great beast\'s fang found in the St. Lamia region.',
    'Moon Bug': 'A type of firefly that glows in the shimmering yellow of the moon',
    'Shadow Cloak': 'Unit is stealthed for the first two turns of battle. BB gauge fills much faster when obtaining BC',
    'Flower Stud': 'Adds chance of BB gauge greatly filling when dealing Spark damage ',
    'Demon Shard': 'Slightly increases BB gauge after every turn',
    'Honor Bone': 'Unique bones distributed by the Summoners\' Council.',
    'Musa Feather': 'A feather from the Musa, a bird said to be loved by the gods.',
    'Dragon Sword': 'Greatly Increases Atk and Critical Hit Rate when Near Death',
    'Blood Scythe': 'Adds Possible Injury Effect and Absorbs HP from normal attacks',
    'Lost Claw': 'A bright red claw from one of the upper arms of Mistzug.',
    'Fire Blade': 'Boosts Max HP, Def by 5% and Increase Fire Atk for Fire Type Unit by 20%',
    'Charge Stone': 'Boosts Rec by 10%, and Increased Critical Chance',
    'Dragon Studs': 'Adds chance of BB greatly filling when attacking',
    'Heth Feather': 'A feather from the Hess, the mother of all birds.',
    'Grief Eye': 'A black crystal that can be uncovered in old battlegrounds.',
    'Demon Flag': 'Boosts BB gauge when an enemy is defeated & when a battle is won',
    'Spice Pouch': 'A pouch filled with cooking necessities',
    'Tech Gizmo 2': 'Greatly increases drop rate of BC when attacking',
    'Beryl Pelt': 'The pelt of a great bird called the "Beryl Bird."',
    'Death Axe': 'Boosts Critical Rate when HP is Full',
    'Abyss Sword': 'Boosts Atk, Def, Rec, and HP by 25%',
    'Divine Jewel': 'Greatly increases Atk when BB gauge is full',
    'Riff Feather': 'A red wing from a butterfly that is rarely seen nowadays.',
    'Holy Gear': 'A piece of Van Lucy that closely resembles machinery.',
    'Hollow Rock': 'An uncommon stone with no elemental powers.',
    'Calamity Eye': 'An eye within Nalda Delia\'s torso that hides terrible magic.',
    'Paladin Stone': 'A stone that has special elemental defense powers.',
    'Worship Cane': 'Boosts Rec by 35%',
    'Dogma Shield': 'Boosts Def by 30%',
    'Sky Staff': 'Boosts Rec by 20%',
    'Divine Robe': 'Adds Chance of Damage Taken being Decreased by 30%',
    'Rainbow Hide': 'A glimmering rare hide. Unique crafting material',
    'Shiny Anklet': 'Increases amount of hits, and greatly boosts Atk',
    'Move Feather': 'The molted feathers of a black bird that soars among powerful monsters.',
    'Tidal Shield': 'Decrease Water Damage by 30%',
    'Death Scythe': 'Boosts Atk and Critical Hit Rate when HP is Below Half',
    'Glowing Bug': 'A glowing bug native to the lands of Agni.',
    'Adamite Shard': 'An extremely durable material mined from the depths of earth. Unique crafting material',
    'Mow Nut': 'A very poisonous nut that grows everywhere in Grand Gaia.',
    'Ragna Blade': 'Boosts Atk by 50% and adds chance of ignoring enemy\'s Def when attacking',
    'Royal Crest': 'Recovers HP when a Battle is Won',
    'Champion Axe': 'Boosts Critical Hit Rate',
    'Burny\'s Soul Stone': 'Boosts Atk, Def, Rec, and max HP by 10%',
    'Yellow Pelt': 'The pelt from the king of the golden beasts.',
    'Prized Jewel': 'A valuable piece of polished crystal stone',
    'Medulla Gem': 'Boosts Atk, Def, Rec, and max HP by 20%',
    'Dark Stone': 'A piece of Reduhark\'s black wings.',
    'Blood Bone': 'A special bone said to reside within people of extraordinary magic power.',
    ' XXX Soul Spear': 'Adds Chance of Absorbing HP when Attacking',
    'Omni Gizmo': 'Increases drop rate of BC and HC when attacking',
    'Bahamut Rage': 'Boosts max HP & Atk by 15%',
    'Tree Shield': 'Boosts Def & Rec by 15%',
    'Dragon Blade': 'Boosts Atk by 20%',
    'Royal Light': 'Increases resistance to Weak, Injury, and Paralysis',
    'Sacred Jewel': 'Boosts Atk, Def, Rec, and Max HP by 15%',
    'Rhau Feather': 'Feathers of the giant Rhau that are materials for weapons and armor.',
    'Silver Pelt': 'The pelt of a silver wolf rumored to have gone extinct millennia ago.',
    'Ally Savior': 'Boosts all abilities when BB gauge is full',
    'Mino Shard': 'A chipped piece from a minotaur\'s horn. Unique crafting material',
    'Cure Gizmo 2': 'Greatly increases drop rate of HC when attacking',
    'Theo Feather': 'The naturally molted feathers of a migratory bird called Theo.',
    'Fujin\'s Eye': 'A crystal that sparkles based on the spiritual energy of its holder.',
    'Star Blade': 'Boosts BB Gauge when an Enemy is Defeated',
    'Chaos Sword': 'Boosts Atk, Def, Rec, and max HP by 20%',
    'Order Staff': 'Boosts Rec by 30%',
    'Spirit Stone': 'A magical stone rarely discovered in Grand Gaia.',
    'Prized Cloth': 'Adds Chance of Damage Taken being Decreased by 25%',
    'King\'s crown_test': 'Adds Chance of BB Gauge Filling when Attacked',
    'Blue Drop': 'Drops of extremely sweet water found all over Elgaia and Grand Gaia. ',
    'Holy Robe': 'Boosts Max HP by 15%',
    'Fake Stone': 'BB gauge increases greatly after every turn',
    'Venom Shard': 'Negates Poison',
    'God Armor': 'Boosts Max HP by 25%',
    'Venom Knives': 'Adds possible Poison effect to normal attack',
    'Heavenly Bud': 'Increases damage dealt during Spark by 100%',
    'Speed Star': 'Adds chance of ignoring enemy\'s Def when attacking',
    'Curse Shard': 'Negates Curse',
    'Scaly Pelt': 'A scale of Laguna Rex that can deflect heat.',
    'Spirit Armor': 'Boosts Max HP by 5%',
    'Thunder Chip': 'A piece of the thunder beast\'s Thunder Bone.',
    'Mimic Bug': 'A bug that can camouflage itself, adapting to everything.',
    'Spark Geyser': 'Increases damage dealt during Spark by 50%',
    'Brave Crest': 'Boosts Atk, Def, Rec, and max HP by 10%',
    'Goddess Seal': 'Boosts Def by 15%',
    'Seal Sword': 'Boosts max HP & Atk by 30%',
    'Red Claw': 'The red fossil of a great beast\'s claw found in the St. Lamia region.',
    'Giant Shield': 'Boosts Def by 5%',
    'Dark Eye': 'A crystal that holds the power of dark.',
    'Thief Gloves': 'Increases drop rate of Zel, Karma, and Items when attacking',
    'Dark Bone': 'The marrow of a wing from Reduhark.',
    'Health Charm': 'Increases resistance to all status ailments',
    'Smoky Drop': 'Smoky-looking drops that release a putrid gas, found among clusters of special fungi.',
    'Blue Bug': 'A small blue ladybug.',
    'Red Drop': 'Slight red drops from famed springs with a powerful recovery effect.',
    'Unicorn Shard': 'A chipped piece from a unicorn\'s horn. Unique crafting material',
    'Earth Shield': 'Decreases Earth Damage by 15%',
    'Wicked Tear': 'A mysterious liquid that leaked out from the head of Van Nader.',
    'Heaven Sword': 'Increases Atk and Def by 10%',
    'Thunder Bone': 'A thunder beast\'s organ that extends from its back to its belly.',
    'Divine Sword': 'Boosts Atk by 25%',
    'Dream Stone': 'A fascinating stone said to enhance dreaming when held during sleep.',
    'Mech Sword': 'Boosts Atk, Def, Rec, and Max HP by 5%',
    'Doom Jewel': 'A jewel rumored to be the origin of Nalda Delia\'s power.',
    'Demon Shield': 'Boosts Def & Rec by 30%',
    'Twinkle Gem': 'Renders all status ailments invalid, and increases BB gauge every turn',
    'Gospel Stone': 'A magical stone said to have the divine protection of the gods.',
    'Yellow Grass': 'A holy grass native to the grasslands in front of Lucius\' Gate.',
    'Tidal Eye': 'A gold crystal whose effects and proper use are shrouded in mystery.',
    'Alpha Shield': 'Boosts Def & Rec by 25%',
    'Zeus\'s Bow': 'Adds possible Paralysis effect to normal attack',
    'Geldnite Axe': 'Massively boosts critical hit rate and doubles critical hit damage',
    'Death Spear': 'Adds Chance of Absorbing a Great Deal of HP when Attacking',
    'Goddess Flag': 'Replenishes HP when an enemy is defeated & when a battle is won',
    'Golden Fang': 'A fang from the king of all the long yellow haired beasts.',
    'Water Eye': 'A crystal that holds the power of water.',
    'Buru Nut': 'The nut from a perennial Bue plant, native all over Elgaia.',
    'Moonlit Essence': 'Pure water, infused with lunar magic',
    'Meru Nut': 'A nut from Meru-Meru that has an unusually hard shell.',
    'Abyss Stone': 'A stone that absorbs all light, like a dark abyss.',
    'Wicked Eye': 'A crystal from Van Nader in the shape of an eyeball.',
    'Memory Stone': 'A stone collected from a battlefield where many heroes were lost.',
    'Death Jewel': 'Boosts Atk, Def, Rec & max HP by 10%',
    'Thunder Bow': 'Adds Possible Paralysis Effect to Normal Attack',
    'Green Grass': 'A plant used in cures that typically inhabits every area of Elgaia.',
    'Blue Pelt': 'The blue pelt of a tough beast.',
    'Shiny Nut': 'A rare nut that grows on the back of Laguna Rex.',
    'Fire Eye': 'A crystal that holds the power of fire.',
    'Poison Light': 'Increases Resistance to Poison',
    'Lynn Feather': 'Harpy Feathers said to be wholly composed of poison.',
    'Muramasa': 'Boosts Atk by 50% for First 2 Turns',
    'Silver Drop': 'A drop from the waters which flow around the temple Arlon.',
    'Lament Blade': 'Boosts greatly Atk when HP is low',
    'Ares\' Crest': 'Boosts BB Gauge when a Battle is Won',
    'Angel Sword': 'Boosts max HP & Atk by 25%',
    'Soul Bracer': 'Boosts Drop Rate of Karma when Attacking',
    'Masamune': 'Boosts Atk and Def by 75% for first 2 turns',
    'Miroku Pearl': 'BB gauge refills slightly faster',
    'Purple Bone': 'The bone of a wolf that was protected by a dark goddess.',
    'Steeple Rose': 'Increases damage dealt during Spark by 50%',
    'Death Sword': 'Boosts Atk, Def, Rec, and max HP by 15%',
    'Wicked Blade': 'Greatly boosts all abilities when HP is full',
    'Prized Stone': 'The most valuable stone in existence, found in the Sacred Mt. Craylia.',
    'Rouge Stone': 'A mineral ore extracted from a red rock found in the wastelands of Agni.',
    'White Bangle': 'Boosts effectiveness of HC',
    'Clear Cloak': 'Decreases Chance of Being Targeted',
    'Light Eye': 'A crystal that holds the power of light.',
    'Holy Circuit': 'A piece of Van Nader that closely resembles machinery.',
    'Star Helm': 'Adds Chance of 20% of Damage Taken Being Recovered',
    'Azure Pelt': 'A rarely seen blue beast pelt.',
    'Miracle Drop': 'Drop formed from the dew around the area where the Vortex emerges',
    'Numb Light': 'Increases Resistance to Paralysis',
    'Blood Pelt': 'A beautifully patterned beast pelt often displayed by enthusiasts.',
    'Creator\'s Blade': 'Immensely strengthens the bearer, granting god-like abilities.',
    'Ruin Helm': 'Adds Chance of Returning 30% of Damage Taken to Enemy when Attacked',
    'Star Dust': 'The remains of a fallen star. Unique crafting material.',
    'Honor Fang': 'Unique fangs distributed by the Summoners\' Council.',
}